// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-availability.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var get_availability_default = defineTool({
  name: "get_availability",
  title: "Get consultation availability",
  description: "Return the set of already-booked consultation slot start times (ISO UTC) between two dates. Any working-hour slot NOT in this list is available. Slots are 1 hour, Mon-Fri, Kigali time (CAT/UTC+2), at 09:00, 10:00, 11:00, 14:00, and 15:00 local.",
  inputSchema: {
    fromIso: z.string().describe("Start of the range, ISO 8601 UTC (e.g. 2026-07-20T00:00:00Z)."),
    toIso: z.string().describe("End of the range, ISO 8601 UTC. Must be within 8 weeks of now.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ fromIso, toIso }) => {
    const url = `${process.env.SUPABASE_URL}/functions/v1/get-availability`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY,
        Authorization: `Bearer ${process.env.SUPABASE_PUBLISHABLE_KEY}`
      },
      body: JSON.stringify({ fromIso, toIso })
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok) {
      return {
        content: [{ type: "text", text: body.error ?? `HTTP ${res.status}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(body, null, 2) }],
      structuredContent: body
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_bookings_default = defineTool2({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List consultation bookings for the signed-in user (matched by their account email).",
  inputSchema: {
    includeCancelled: z2.boolean().optional().describe("Include cancelled bookings. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeCancelled }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on account" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select("id, slot_start, slot_end, status, matter_type, message, cancellation_token").eq("client_email", email).order("slot_start", { ascending: false }).limit(50);
    if (!includeCancelled) query = query.neq("status", "cancelled");
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-booking.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_booking_default = defineTool3({
  name: "create_booking",
  title: "Book a consultation",
  description: "Book a 1-hour consultation slot for the signed-in user. slotStartUtc must be an available working-hour slot returned by get_availability (Mon-Fri, 09:00/10:00/11:00/14:00/15:00 Kigali time). The booking is made under the signed-in user's account email.",
  inputSchema: {
    slotStartUtc: z3.string().describe("ISO 8601 UTC start of the slot."),
    name: z3.string().min(1).describe("Client full name."),
    phone: z3.string().optional(),
    organization: z3.string().optional(),
    entityType: z3.string().optional().describe("Individual, Company, NGO, etc."),
    jurisdiction: z3.string().optional().describe("Country or region of the matter."),
    matterType: z3.string().optional().describe("Area of law (e.g. Corporate, Litigation, Tax)."),
    message: z3.string().optional().describe("Short description of the matter.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on account" }], isError: true };
    }
    const start = new Date(input.slotStartUtc);
    if (Number.isNaN(start.getTime())) {
      return { content: [{ type: "text", text: "Invalid slotStartUtc" }], isError: true };
    }
    const slotEndUtc = new Date(start.getTime() + 60 * 6e4).toISOString();
    const url = `${process.env.SUPABASE_URL}/functions/v1/create-booking`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY,
        Authorization: `Bearer ${process.env.SUPABASE_PUBLISHABLE_KEY}`
      },
      body: JSON.stringify({
        slotStartUtc: start.toISOString(),
        slotEndUtc,
        client: {
          name: input.name,
          email,
          phone: input.phone,
          organization: input.organization,
          entityType: input.entityType,
          jurisdiction: input.jurisdiction,
          matterType: input.matterType,
          message: input.message
        }
      })
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok || body.ok === false) {
      return {
        content: [{ type: "text", text: body.error ?? `HTTP ${res.status}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: `Booking confirmed for ${start.toISOString()}` }],
      structuredContent: body
    };
  }
});

// src/lib/mcp/tools/cancel-booking.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var cancel_booking_default = defineTool4({
  name: "cancel_booking",
  title: "Cancel a booking",
  description: "Cancel one of the signed-in user's consultation bookings. Look up the booking with list_my_bookings first to get its cancellation_token. Cancellations within 24 hours of the appointment are subject to the full consultation fee.",
  inputSchema: {
    cancellationToken: z4.string().describe("cancellation_token from list_my_bookings."),
    reason: z4.string().optional().describe("Optional cancellation reason.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ cancellationToken, reason }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on account" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: rows, error: lookupErr } = await supabase.from("bookings").select("id, client_email, status").eq("cancellation_token", cancellationToken).limit(1);
    if (lookupErr) {
      return { content: [{ type: "text", text: lookupErr.message }], isError: true };
    }
    if (!rows || rows.length === 0 || rows[0].client_email !== email) {
      return {
        content: [{ type: "text", text: "Booking not found for this account." }],
        isError: true
      };
    }
    const url = `${process.env.SUPABASE_URL}/functions/v1/cancel-booking`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY,
        Authorization: `Bearer ${process.env.SUPABASE_PUBLISHABLE_KEY}`
      },
      body: JSON.stringify({ token: cancellationToken, reason })
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok || body.ok === false) {
      return {
        content: [{ type: "text", text: body.error ?? `HTTP ${res.status}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: "Booking cancelled." }],
      structuredContent: body
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fgssohxuivvejtcdbgod";
var mcp_default = defineMcp({
  name: "beacon-attorneyes-mcp",
  title: "Beacon Attorneyes & Consultants",
  version: "0.1.0",
  instructions: "Tools for the Beacon Attorneyes & Consultants law firm site. Use `get_availability` to find open consultation slots, `create_booking` to book one under the signed-in user, `list_my_bookings` to see the user's bookings, and `cancel_booking` to cancel one. All booking tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_availability_default,
    list_my_bookings_default,
    create_booking_default,
    cancel_booking_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
